### PR TITLE
#5, #6, #7, #8 Pages content

### PR DESCRIPTION
**Pull request by ioulungTsai**

### CODE REVIEW

**Comment by chunyenHuang** [comment]
Can you use icon instead in the contact page?
https://ioulungtsai.github.io/personal-website/contact

**Comment by chunyenHuang** [comment]
Can you add screenshots in the project page?
https://ioulungtsai.github.io/personal-website/projects

**Comment by chunyenHuang** [comment]
Can you unify the font sizes, probably just use 2-3 font sizes for the whole website?

**Comment by ioulungTsai** [comment]
> Can you use icon instead in the contact page?
> https://ioulungtsai.github.io/personal-website/contact

Please check again, note me if any concerns, thank you!

**Comment by ioulungTsai** [comment]
> Can you unify the font sizes, probably just use 2-3 font sizes for the whole website?

Please check again, note me if any concerns, thank you

**Comment by ioulungTsai** [comment]
> Can you add screenshots in the project page?
> https://ioulungtsai.github.io/personal-website/projects

Please check again, note me if any concerns, thank you!

**Comment by chunyenHuang** [comment]
Looks good.

**Pull request merged**
