### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by ioulungTsai**
Will deploy website to GitHub Pages for review by tomorrow.

### CODE REVIEW

**Comment by chunyenHuang** [comment]
Can you launch a demo site in gitpage or heroku for this PR?

**Comment by ioulungTsai** [comment]
> Can you launch a demo site in gitpage or heroku for this PR?

https://ioulungtsai.github.io/mywebsite-demo/

**Comment by chunyenHuang** [comment]
When I click the left top title, it redirects me to `https://ioulungtsai.github.io/` instead of `https://ioulungtsai.github.io/mywebsite-demo/` and it shows 404.

**Comment by ioulungTsai** [comment]
> When I click the left top title, it redirects me to `https://ioulungtsai.github.io/` instead of `https://ioulungtsai.github.io/mywebsite-demo/` and it shows 404.

please check by below url from now on, thank you 
https://ioulungtsai.github.io/personal-website/

**Review by chunyenHuang — APPROVED** [review]
Awesome. Please merge this PR and move on to the next feature.

**Pull request merged**
